package cli

// Regression test for the reconciled migration-note ownership model
// (releaser-owned, cut-time authorship).
//
// A prior read-only solution-brief resolved a contract conflict over who authors
// the consumer migration note `templates/migrations/v<next>.md`:
//   - the shipped domain-free `releaser` (release overlay pack) claimed authorship
//     during Step 3 Prepare; AND
//   - the dogfood-local `harness-release-readiness` G1 gate BLOCKED readiness when
//     the note was absent and DELEGATED its authorship to `docs-steward`.
//
// The DECISION (settled, ground truth): the shipped `releaser` is the SOLE
// semantic author of the note (cut-time, during Prepare); the readiness reporter
// is a read-only authorability gate (note-absent-but-determinable is a PASS,
// `expected_at_cut`; an exact-version canonical note at HEAD is a PASS,
// `resumable_existing_note`); G1 never delegates canonical note authorship to
// `docs-steward`.
//
// This test pins that reconciled contract in BOTH the AUTHORITATIVE overlay
// sources AND their RENDERED MIRRORS, exactly mirroring the pattern of
// TestHarnessDogfood_ReleaseReadinessCarriesG6Gate (the deterministic-content
// contract test for the G6 gate). A regression that restores the contradictory
// ownership edge, drops the cut-time authorship statement, or silently
// re-delegates G1 note authorship to docs-steward fails here.
//
// This is the template/render contract test seam for this slice — it does NOT
// invent a parallel test framework. It lives in `package cli` alongside
// release_render_test.go and harness_dogfood_render_test.go, reuses the
// findModuleRoot helper, and asserts via strings.Contains (the same surface the
// G6 content contract uses).

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// releaseNoteOwnershipReleaserPaths are the AUTHORITATIVE source (the domain-free
// embedded release pack) AND its 1:1 RENDERED MIRROR for the releaser agent.
// The source is embedded into the binary via go:embed, so the mirror is
// regenerated by `make build && vh-agent-harness update` — never hand-edited.
var releaseNoteOwnershipReleaserPaths = []string{
	filepath.Join("templates", "overlays", "release", "agents", "releaser.md"),
	filepath.Join(".opencode", "agents", "releaser.md"),
}

// releaseNoteOwnershipReadinessPaths are the AUTHORITATIVE source (dogfood-local
// overlay pack) AND its 1:1 RENDERED MIRROR for the readiness reporter. The
// dogfood pack is read from disk at runtime, so the mirror regenerates via
// `vh-agent-harness update`.
var releaseNoteOwnershipReadinessPaths = []string{
	filepath.Join(".vh-agent-harness", "overlays", "harness-dogfood", "agents", "harness-release-readiness.md"),
	filepath.Join(".opencode", "agents", "harness-release-readiness.md"),
}

// releaseNoteOwnershipCallableGraphPath is the RENDERED MIRROR of the callable
// graph. The dogfood pack's callable-graph-snippet.md is appended to the core
// graph at this path during render. There is no separate source read here
// because the assertion is about the RENDERED ownership edges (the surface a
// regression can silently restore); the snippet source is covered transitively
// by the same content landing in the mirror.
var releaseNoteOwnershipCallableGraphPath = filepath.Join(".opencode", "docs", "agents", "callable-graph.md")

// containsCheck is a single assertion: name + the substring that MUST be present.
type containsCheck struct{ name, needle string }

// absentCheck is a single negative assertion: name + the substring that MUST be
// ABSENT (used to pin the removed/contradictory ownership edges stay removed).
type absentCheck struct{ name, needle string }

// normalizeWS collapses every run of whitespace (spaces, tabs, newlines) in s to
// a single ASCII space and trims the ends. The overlay sources under test are
// prose markdown hard-wrapped at ~78 columns, so a contract phrase a regression
// can delete frequently spans a line boundary (e.g.
// "MUST NOT author or create a\n   second note commit"). Normalizing both the
// haystack and the needle makes the substring checks robust to re-wrapping
// without weakening the contract — the distinctive words still must appear in
// order. Mirrors the spirit of the G6 test's short distinctive tokens but allows
// longer multi-clause contract sentences to be pinned.
func normalizeWS(s string) string {
	fields := strings.Fields(s)
	return strings.Join(fields, " ")
}

// runContains checks every needle MUST be present in got (after whitespace
// normalization on both sides, so line wrapping does not cause a false miss).
func runContains(t *testing.T, label, got string, checks []containsCheck) {
	t.Helper()
	norm := normalizeWS(got)
	for _, c := range checks {
		if !strings.Contains(norm, normalizeWS(c.needle)) {
			t.Errorf("%s: missing %s — %q (reconciled release-note ownership content drifted out)", label, c.name, c.needle)
		}
	}
}

// runAbsent checks every needle MUST be absent from got (after whitespace
// normalization) — catches a regression that restores a removed/contradictory
// ownership edge.
func runAbsent(t *testing.T, label, got string, checks []absentCheck) {
	t.Helper()
	norm := normalizeWS(got)
	for _, c := range checks {
		if strings.Contains(norm, normalizeWS(c.needle)) {
			t.Errorf("%s: must NOT contain %s — %q (the removed/contradictory ownership edge was restored)", label, c.name, c.needle)
		}
	}
}

// readModuleFile reads a module-root-relative file, fataling on miss.
func readModuleFile(t *testing.T, root, rel string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(body)
}

// TestReleaseNoteOwnership_ReleaserSoleAuthor pins the releaser-side of the
// reconciled contract in BOTH the authoritative source (embedded release pack)
// AND its rendered mirror. Covers:
//   - (a) the shipped releaser remains the SOLE canonical note author;
//   - (g) the releaser contract requires the note at current HEAD before tagging;
//   - (h) a valid already-committed note does not require a second note commit.
func TestReleaseNoteOwnership_ReleaserSoleAuthor(t *testing.T) {
	root := findModuleRoot(t)
	for _, rel := range releaseNoteOwnershipReleaserPaths {
		got := readModuleFile(t, root, rel)
		runContains(t, rel, got, []containsCheck{
			// (a) sole semantic author of the release migration note.
			{"sole semantic author statement", "SOLE semantic author of the release migration note"},
			// cut-time authoring lifecycle states are named in the releaser contract.
			{"resumable_existing_note lifecycle", "resumable_existing_note"},
			// (g) Execute gate: note must be at current HEAD before tagging.
			{"Execute MUST NOT begin unless", "Execute MUST NOT begin unless the"},
			{"exact-version canonical note committed at HEAD", "exact-version canonical note is committed at current HEAD"},
			// (h) idempotency: a valid already-committed note must not get a second commit.
			{"MUST NOT author or create a second note commit", "MUST NOT author or create a second note commit"},
		})
	}
}

// TestReleaseNoteOwnership_ReadinessG1Gate pins the readiness-side of the
// reconciled contract in BOTH the authoritative source (dogfood overlay pack)
// AND its rendered mirror. Covers:
//   - (b) G1 no longer assigns note authorship to docs-steward (incl. the
//     delegated_owners G1 edge moved OFF docs-steward);
//   - (c) G3 docs gaps still direct to docs-steward (unchanged);
//   - (d) G1 recognizes expected_at_cut and resumable_existing_note;
//   - (e) the report schema includes migration_note_coverage.
func TestReleaseNoteOwnership_ReadinessG1Gate(t *testing.T) {
	root := findModuleRoot(t)
	for _, rel := range releaseNoteOwnershipReadinessPaths {
		got := readModuleFile(t, root, rel)
		runContains(t, rel, got, []containsCheck{
			// G1 is a read-only authorability gate (does NOT author/edit/commit).
			// Source capitalizes as "READ-ONLY authorability gate".
			{"G1 read-only authorability gate", "READ-ONLY authorability gate"},
			// (b) G1 does NOT require docs-steward to author the canonical note.
			{"does NOT require docs-steward to author", "does NOT require `docs-steward` to author"},
			// (b) G1 NEVER delegates canonical note authorship to docs-steward.
			{"NEVER delegates canonical note authorship to docs-steward", "NEVER delegates canonical note authorship to `docs-steward`"},
			// (b) delegated_owners G1 edge is now on releaser, not docs-steward.
			{"delegated_owners G1 -> releaser", `{ "for": "G1", "to": "releaser"`},
			// (c) delegated_owners G3 edge stays on docs-steward (unchanged).
			{"delegated_owners G3 -> docs-steward", `{ "for": "G3", "to": "docs-steward"`},
			// (d) G1 recognizes expected_at_cut.
			{"G1 expected_at_cut", "expected_at_cut"},
			// (d) G1 recognizes resumable_existing_note.
			{"G1 resumable_existing_note", "resumable_existing_note"},
			// (e) report schema includes migration_note_coverage.
			{"migration_note_coverage field", "migration_note_coverage"},
		})
		// (b) negative: the old delegated_owners G1 reason ("author the migration
		// note", distinctive to the removed docs-steward G1 entry) must NOT be
		// present — it would mean the contradictory edge was restored.
		runAbsent(t, rel, got, []absentCheck{
			{"removed G1 docs-steward reason", "author the migration note"},
		})
	}
}

// TestReleaseNoteOwnership_CallableGraphNoContradictoryEdge pins the rendered
// callable graph: the readiness→docs-steward edge is G3 documentation-coverage
// remediation ONLY and explicitly does NOT confer migration-note ownership,
// while the readiness→releaser handoff may carry the reconciled lifecycle
// states. Covers:
//   - (f) the rendered callable graph does not restore the contradictory
//     ownership edge (the old "G1 migration-note authorship" docs-steward edge
//     must stay gone).
func TestReleaseNoteOwnership_CallableGraphNoContradictoryEdge(t *testing.T) {
	root := findModuleRoot(t)
	got := readModuleFile(t, root, releaseNoteOwnershipCallableGraphPath)
	runContains(t, releaseNoteOwnershipCallableGraphPath, got, []containsCheck{
		// readiness→docs-steward edge is G3 documentation-coverage remediation ONLY.
		{"G3 docs-coverage remediation ONLY", "G3 documentation-coverage remediation ONLY"},
		// canonical migration-note authorship belongs to the releaser.
		{"canonical migration-note authorship belongs", "canonical migration-note authorship belongs"},
		// readiness→releaser handoff may carry the reconciled lifecycle states.
		{"handoff expected_at_cut", "expected_at_cut"},
		{"handoff resumable_existing_note", "resumable_existing_note"},
	})
	// (f) negative: the old contradictory edge text ("G1 migration-note
	// authorship" as a docs-steward delegation) must NOT be present in the
	// rendered graph. This is the exact phrase the pre-reconciliation
	// callable-graph-snippet carried for the readiness→docs-steward G1 edge.
	runAbsent(t, releaseNoteOwnershipCallableGraphPath, got, []absentCheck{
		{"old contradictory G1 docs-steward edge", "G1 migration-note authorship"},
	})
}
