package ownership

import (
	"fmt"
	"sort"
	"strings"
)

// Class is one of the six armed ownership classes (see package doc). It is the
// S2 update-safety classification for a single path.
type Class string

const (
	// ClassPlatformManaged: platform owns; platform updates overwrite. Lowest
	// protection on the raise/lower lattice. Plain-mutable by the platform.
	ClassPlatformManaged Class = "platform_managed"

	// ClassPlatformArmed: platform owns; platform updates, but only via an
	// armed/disposition path (propose-then-gated-apply). One step above plain
	// overwrite.
	ClassPlatformArmed Class = "platform_armed"

	// ClassOverlayExtension: platform owns the managed blocks; the project may
	// extend. Platform-merged, never wholesale-overwritten. Highest hand-
	// protection that still permits platform-authored blocks.
	ClassOverlayExtension Class = "overlay_extension"

	// ClassProjectOwned: project owns; the platform NEVER touches it on update
	// (seed once, then never-touch). Highest hand-protection on the lattice.
	ClassProjectOwned Class = "project_owned"

	// ClassExternalGenerated: derived/generated by an external provider version
	// pin. OFF the raise/lower lattice; not hand-overridable and not a plain
	// platform-mutable target (drift-checked against the provider version only).
	ClassExternalGenerated Class = "external_generated"

	// ClassLocalOnly: local runtime/scratch state; not on the platform update
	// path at all. OFF the raise/lower lattice; not hand-overridable.
	ClassLocalOnly Class = "local_only"
)

// allClasses is the exhaustive set of valid armed classes. ParseClass and
// IsValid consult it.
var allClasses = map[Class]bool{
	ClassPlatformManaged:   true,
	ClassPlatformArmed:     true,
	ClassOverlayExtension:  true,
	ClassProjectOwned:      true,
	ClassExternalGenerated: true,
	ClassLocalOnly:         true,
}

// IsValid reports whether c is one of the six armed ownership classes.
func (c Class) IsValid() bool {
	return allClasses[c]
}

// IsHandOverridable reports whether c sits on the raise/lower lattice and may
// therefore be the FROM or TO of a project override. external_generated and
// local_only are OFF the lattice (see package doc).
func (c Class) IsHandOverridable() bool {
	return IsHandOverridable(c)
}

// ParseClass parses a raw string into a Class, returning an error naming the
// offending value and the valid set when it is not one of the six classes. It
// is the input-validation chokepoint for class literals coming from YAML.
func ParseClass(raw string) (Class, error) {
	c := Class(raw)
	if !c.IsValid() {
		return "", &InvalidClassError{Class: raw}
	}
	return c, nil
}

// AllClasses returns the six armed classes in canonical (lattice-first,
// off-lattice-last) order. Useful for help text and deterministic iteration.
func AllClasses() []Class {
	return []Class{
		ClassPlatformManaged,
		ClassPlatformArmed,
		ClassOverlayExtension,
		ClassProjectOwned,
		ClassExternalGenerated,
		ClassLocalOnly,
	}
}

// validClassList is the comma-separated class set used in error guidance. It is
// computed once and rendered sorted for stable messaging.
var validClassList = func() string {
	all := AllClasses()
	out := make([]string, len(all))
	for i, c := range all {
		out[i] = string(c)
	}
	sort.Strings(out)
	return strings.Join(out, " | ")
}()

// invalidClassGuidance is the shared hint appended to InvalidClassError so an
// operator sees the valid vocabulary inline.
const invalidClassGuidance = "must be one of the six armed ownership classes"

// InvalidClassError is returned when an override (or a platform default)
// carries a class literal that is not one of the six armed classes. It is the
// "fail closed on garbage" guard before any lattice reasoning is applied.
//
// Detectable via errors.As:
//
//	var ICE *ownership.InvalidClassError
//	if errors.As(err, &ICE) { ... }
type InvalidClassError struct {
	// Class is the offending literal value.
	Class string
}

// Error implements the error interface.
func (e *InvalidClassError) Error() string {
	return fmt.Sprintf("ownership: invalid class %q (%s: %s)", e.Class, invalidClassGuidance, validClassList)
}
