// Package ownership implements the S2 update-safety classification surface and
// the D2-A monotonic (raise-only) override rule for the agent-harness shim.
//
// Authority domain (the config-authority model §S2). harness-ownership.yml owns
// the update-safety classification: for each managed/generated/artifact path,
// its ARMED ownership class, its update verb, and its provenance. The EFFECTIVE
// ownership map is computed from two inputs:
//
//   - Platform module rules (upstream, versioned with the harness): the default
//     armed class for every path a module materializes.
//   - Project overrides (the consumer-repo harness-ownership.yml): project-
//     authored amendments.
//
// with PROJECT-WINS precedence ON CONFLICT — but only when the override is a
// valid RAISE. This package is the mechanical enforcement of that rule.
//
// # The armed ownership classes
//
// Six classes (see Class constants and spike1/harness-ownership.yml):
//
//   - platform_managed   : platform owns; platform updates overwrite.
//   - platform_armed     : platform owns; platform updates, but via an armed/
//     disposition path (a step up from plain overwrite).
//   - overlay_extension  : platform owns managed blocks; project may extend
//     (platform-merged, not wholesale overwrite).
//   - project_owned      : project owns; platform NEVER touches on update
//     (highest hand-protection).
//   - external_generated : derived/generated by an external provider version pin;
//     not hand-edited.
//   - local_only         : local runtime/scratch state; not on the platform
//     update path at all.
//
// # The raise-only lattice (D2-A in v0)
//
// Per the design notes (Slice 4), ordinary harness-ownership.yml
// overrides are MONOTONIC / RAISE-ONLY. A project may only RAISE protection.
// The total protection ordering over the four platform-vs-project classes is:
//
//	platform_managed < platform_armed < overlay_extension < project_owned
//
// Accepted (raise) examples from the brief:
//
//	platform_managed  -> platform_armed    : accepted (raise)
//	platform_managed  -> project_owned     : accepted (raise)
//	overlay_extension -> project_owned     : accepted (raise)
//
// Rejected (downgrade) examples:
//
//	project_owned    -> platform_managed   : rejected (downgrade)
//	platform_armed   -> platform_managed   : rejected (downgrade)
//
// A downgrade is NOT representable as ordinary config drift: Resolve rejects it
// with a typed *DowngradeError whose guidance points to the future reviewed /
// scary downgrade workflow (held beyond v0; see the design notes
// Slice 6). This enforces the armed-ownership guarantee that motivated the whole
// shim: Copier cannot protect per-file ownership, so the shim must, and it must
// never let ordinary config weaken it.
//
// # Off-lattice classes (external_generated, local_only)
//
// external_generated and local_only are OFF the raise/lower lattice. Their class
// is determined by the platform / provider / local convention, never by a hand
// override:
//
//   - external_generated: derived by an external provider version pin. Hand-
//     overriding it would either suppress drift-checking (dangerous) or pretend
//     hand-ownership of generated output (incoherent).
//   - local_only: local scratch / runtime state. Raising it to project_owned is
//     redundant (already never touched); lowering it to platform_managed would
//     be catastrophic (platform would overwrite local operator state); and the
//     local_only <-> project_owned pair is genuinely ambiguous, so this package
//     FAILS CLOSED on it rather than silently picking a side.
//
// Therefore an override whose FROM or TO class is external_generated or
// local_only is rejected with *NotHandOverridableError.
//
// # Fail-closed posture
//
// Every unrecognized or weakening edit fails closed with a typed, self-
// explaining error rather than silently inventing a class or disarming a path:
//
//   - unknown override path (no platform default)         -> *UnknownPathError
//   - invalid class literal (not one of the six)          -> *InvalidClassError
//   - override on/from/to an off-lattice class            -> *NotHandOverridableError
//   - override that lowers protection on the lattice      -> *DowngradeError
//
// All four are errors.As-detectable. Resolve collects every violation and joins
// them so an operator sees the full picture in one pass.
//
// # Update-path respect
//
// IsMutableByPlatform reports whether an UNGATED platform render/overwrite may
// touch a path of the given class. Only platform_managed is plain-mutable; every
// other class (including project_owned) is not. The wiring of IsMutableByPlatform
// into the live render/upgrade path is a follow-up: the prototype's manifest
// (internal/manifest) currently uses a parallel simpler class vocabulary
// (managed / generated-from-config / project-owned) and already protects its
// project-owned class via manifest.IsRenderable; the armed-class update-path
// gate lands when the manifest converges on the armed classes. See ordering.go.
package ownership
