package schema

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// RepoRecon is the schema for repo-recon structural data (entrypoints, hotspots,
// packages, tests). Ownership class: external_generated (the repo-recon generator
// — a platform_managed skill that creates/incrementally-updates/recreates
// project-scoped structure assets — is the provider).
//
// Reconcile is regenerate-class: the provider owns the data, so reconcile returns
// OutcomeNoop on update (the generator regenerates the file rather than the
// substrate merging it). doctor validates the shape against the contract so a
// hand-edited/corrupted recon data file is caught. The generator itself lands in
// Slice 3; this file is the contract.
type RepoRecon struct{}

// repoReconAllowedTopLevel is the exhaustive set of top-level keys a repo-recon
// data file may carry.
var repoReconAllowedTopLevel = map[string]bool{
	"entrypoints": true,
	"hotspots":    true,
	"packages":    true,
	"tests":       true,
}

// Validate reports structural problems in a repo-recon data file. Each top-level
// section must be the right shape: entrypoints/hotspots/tests are arrays of
// objects with at least a name/path; packages is a map keyed by package name.
func (RepoRecon) Validate(raw []byte) []FieldError {
	if len(strings.TrimSpace(string(raw))) == 0 {
		return []FieldError{{Field: "<root>", Message: "file is empty"}}
	}
	var root map[string]any
	if err := yaml.Unmarshal(raw, &root); err != nil {
		return []FieldError{{Field: "<root>", Message: fmt.Sprintf("not valid YAML: %v", err)}}
	}
	var errs []FieldError

	keys := make([]string, 0, len(root))
	for k := range root {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if !repoReconAllowedTopLevel[k] {
			errs = append(errs, FieldError{
				Field:   k,
				Message: fmt.Sprintf("unknown top-level key %q; allowed: entrypoints, hotspots, packages, tests", k),
			})
		}
	}

	// entrypoints / hotspots / tests must be arrays of objects; packages a map.
	errs = appendReconArrayErrors(errs, root, "entrypoints")
	errs = appendReconArrayErrors(errs, root, "hotspots")
	errs = appendReconArrayErrors(errs, root, "tests")
	if pkgs, ok := root["packages"]; ok {
		if _, ok := pkgs.(map[string]any); !ok {
			errs = append(errs, FieldError{Field: "packages", Message: "must be a map keyed by package name"})
		}
	}
	return errs
}

// appendReconArrayErrors validates one array-of-objects section.
func appendReconArrayErrors(errs []FieldError, root map[string]any, field string) []FieldError {
	v, ok := root[field]
	if !ok {
		return errs
	}
	arr, ok := v.([]any)
	if !ok {
		return append(errs, FieldError{Field: field, Message: "must be an array of objects"})
	}
	for i, el := range arr {
		obj, ok := el.(map[string]any)
		if !ok {
			errs = append(errs, FieldError{
				Field:   fmt.Sprintf("%s[%d]", field, i),
				Message: "must be an object",
			})
			continue
		}
		// Each element must carry a name or path so the recon data is actionable.
		if _, hasName := obj["name"]; !hasName {
			if _, hasPath := obj["path"]; !hasPath {
				errs = append(errs, FieldError{
					Field:   fmt.Sprintf("%s[%d]", field, i),
					Message: "object must carry a 'name' or 'path' key",
				})
			}
		}
	}
	return errs
}

// Reconcile is regenerate-class (external_generated): the substrate does NOT
// merge repo-recon data; the generator regenerates it. On update we return
// OutcomeNoop. doctor is the validation surface.
func (RepoRecon) Reconcile(project, platformDefault []byte) (ReconcileResult, error) {
	return ReconcileResult{
		Outcome: OutcomeNoop,
		Skipped: []string{"repo-recon: external_generated; regenerated by the provider, not merged by the substrate"},
	}, nil
}
